//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public int InventoryId { get; set; }
        public int StyleId { get; set; }
        public string Size { get; set; }
        public int TotalCount { get; set; }
        public int RentingCount { get; set; }
        public int WashingCount { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> RentPrice { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public int Operator { get; set; }
    
        public virtual Styles Styles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}
